# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
matrix:
  include:
    - os: linux
      env:
        - QML_SKIP_GUI_TESTS=1
      before_script:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3 # give xvfb some time to start
        - "export GALLIUM_DRIVER=\"softpipe\""
      julia: 0.6
    - os: osx
      julia: 0.6

notifications:
  email: false

# script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd())'
after_success:
  - julia -e 'cd(Pkg.dir("PlugAndPlot")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))';
