# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.6
notifications:
  email: false

env:
  - DOCUMENTER_DEBUG = true
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia -e 'Pkg.clone(pwd())'
after_success:
  - julia -e 'cd(Pkg.dir("PlugAndPlot")); Pkg.add("Documenter"); include(joinpath("docs", "make.jl"))';
